### ISSUE TITLE
practica modelo de negocios

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo_judith#3]
[PROPUESTA DE VALOR (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo_judith/files/9602961/PROPUESTA.DE.VALOR.1.pdf)

**Comment by EdwinOrtiz1412** [comment]
calificación: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado
